FROM golang:latest AS build-stage
COPY main.go /go/src/app/
WORKDIR /go/src/app/
RUN go mod init
RUN go get -d -v ./...
RUN go install -v ./...
RUN go build -o demo-go-app


FROM golang:alpine AS run-stage
WORKDIR /app
COPY --from=build-stage /go/src/app/demo-go-app /app
CMD ["./demo-go-app"]