apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  labels:
    type: storage
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: standard
  hostPath:
    path: /data/mongodb-data
