apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  labels:
    app: mongo
    type: db
spec:
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: mongo
      labels:
        type: db
    spec:
      containers:
        - image: mongo:4.4
          name: mongo
          ports:
              - containerPort: 27017
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
      volumes:
        - name: mongo-data
          persistentVolumeClaim:
            claimName: mongo-pvc