apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: metadataservice-rc
  labels:
    app: metadataservice
    type: back-end
spec:
  selector:
    matchLabels:
      type: back-end
  template:
    metadata:
      name: metadataservice
      labels:
        type: back-end
    spec:
      containers:
        - image: luckyganesh/metadata-service:v1
          name: metadataservice
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30



