apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    type: db
spec:
  containers:
    - name: mongo
      image: mongo:4.4
      ports:
        - containerPort: 27017
      volumeMounts:
        - name: mongo-data
          mountPath: /data/db
  volumes:
    - name: mongo-data
      emptyDir: {}
